[package]
name = "vesper"
version = "1.0.0"
authors = ["Berkus Decker <berkus@metta.systems>"]
description = "Vesper exokernel"
documentation = "https://doc.metta.systems/vesper"
repository = "https://gitlab.com/metta-systems/vesper"
readme = "README.md"
license = "BSL-1.0"
